### ISSUE TITLE
от какой ветки делать свою ветку?

### ISSUE THREAD

**Issue by olegatro** [Teplitsa/ITVolunteer#44]
Подскажите, от какой ветки делать свою ветку для отправки pull request?

**Comment by olegatro** [comment]
полагаю что нужно делать от ветки `prod`, но стоит перестраховаться :)

**Comment by avdeeva-nataliya** [comment]
Здравствуйте! Да, от prod.

**Comment by olegatro** [comment]
Спасибо :)
